### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by MarkusBernhardt** [javadelight/delight-rhino-sandbox#1]
I would like to use your library in proxy-vole.
https://github.com/MarkusBernhardt/proxy-vole

Therefore it would be great, if you could deploy this library to Macen Central, so I can deploy my library there also.

**Comment by mxro** [comment]
Thank you for raising this issue.

I have started the process of publishing this to Maven Central. Just waiting for approval for inclusion in JCentral. It should be in Maven Central by tomorrow. I will update this issue when it is.

**Comment by mxro** [comment]
Done! Uploaded to Maven central: [delight-rhino-sandbox](https://search.maven.org/#search%7Cga%7C1%7Cdelight-rhino-sandbox).

Hope the dependency works. If there are any issues, let me know!

**Comment by MarkusBernhardt** [comment]
Thanks a lot! Works like a charm.

New proxy-vole version is now also pushed to Maven Central.
