### ISSUE TITLE
Can you provide an update to Rhino version 1.7.13

### ISSUE THREAD

**Issue by gtskaushik** [javadelight/delight-rhino-sandbox#13]

**Comment by javadelight** [comment]
Done and should be included in release `0.0.12` that should be pushed to Maven central too. Please let me know if this works for you!

**Comment by gtskaushik** [comment]
This is perfect :-)

**Comment by gtskaushik** [comment]
When can we expect this in maven central

**Comment by mxro** [comment]
It's published - but seems like it's not showing up in search - if you cannot find it by tomorrow, please ping me 😃

**Comment by gtskaushik** [comment]
I'm able to see it in maven repo today. Thanks

**Comment by mxro** [comment]
Excellent, thanks for letting me know. I will close this issue now!
