### ISSUE TITLE
How to use the higher JS syntax

### ISSUE THREAD

**Issue by 172184221** [javadelight/delight-rhino-sandbox#15]
my English is poor.
I want to use ES6 syntax to execute, do not know how to use it?

**Comment by mxro** [comment]
I think not all ES6 features may be supported by Rhino at this point:

https://github.com/mozilla/rhino/issues/434

But would be happy if anyone else has more accurate info on this!

**Comment by 172184221** [comment]
Hello!

I tried to use the 'let' keyword in ES6. I add code to the "assertcontextfactory()" method_ safeContext.enterContext ().setLanguageVersion( Context.VERSION_ ES6)”。 However, the execution of the test method does not exit.

**Comment by 172184221** [comment]
Thank you for your reply!

I tried to use the 'let' keyword in ES6.

I add code to the "assertcontextfactory()" method_ safeContext.enterContext ().setLanguageVersion( Context.VERSION_ ES6)”。 However, the execution of the test method does not exit.

I've tried to use the let keyword in rhino. I don't know what to do?

**Comment by mxro** [comment]
As said, looks like this may not be supported in Rhino yet: https://mozilla.github.io/rhino/compat/engines.html#ES2015-bindings-let 

If someone knows otherwise, please let me know!

**Comment by OndrejSpanel** [comment]
The `let` keyword is partially supported. The support is good enough for basic use, but it needs to be enabled with a context flag `CONTEXT.VERSION_ES6` (see https://mozilla.github.io/rhino/compat/engines.html and https://github.com/mozilla/rhino/releases/tag/Rhino1_7_11_Release).

I think the context is created in `assertContextFactory`, via `new SafeContext()`, but I do not see any way how to adjust any options for it.

Can I set context flags somehow when this sandboxing package is used?

**Comment by mxro** [comment]
@OndrejSpanel  Thank you for the idea!

Would this be configured here: https://github.com/javadelight/delight-nashorn-sandbox/blob/23ba3d7013528d1eafcc5123507b3a3f71ab07d5/src/main/java/delight/nashornsandbox/internal/NashornSandboxImpl.java#L107 ?

**Comment by OndrejSpanel** [comment]
I am confused. You point into Nashorn sandbox code, this issue is about Rhino sandbox.

**Comment by mxro** [comment]
Sorry my apologies, mixed up the projects! For the Rhino Sandbox it would be modifying: https://github.com/javadelight/delight-rhino-sandbox/blob/master/src/main/java/delight/rhinosandox/internal/SafeContext.java#L36 correct?

**Comment by OndrejSpanel** [comment]
Yes, that sounds exactly like what is needed.

**Comment by mxro** [comment]
See above PR - made the ES language version the default and published new version `0.0.17` to Maven Central (if I did everything correctly there)~
