### ISSUE TITLE
Is org.eclipse.xtend required or optional?

### ISSUE THREAD

**Issue by gschnepp** [javadelight/delight-rhino-sandbox#21]
xtend.lib requires xtext.xbase.lib which in turn requires Guava. Since all Guava's dependencies changed from optional to required from Guava 22.0 on (Guava 21.0 dependencies in delight-rhino-sandbox 0.0.13 are all optional and ok for me), this also imports com.google.code.findbugs:jsr305:3.0.2 which - tadaa! - can't be used in Eclipse RCP or Eclipse plug-in environments due to collision with an existing "standard" javax.annotation library in the eclipse plugins folder. JSR305 library contains the same java.annotation package which is not easy to work around since Java 9. (More details here: https://nipafx.dev/jsr-305-java-9/)

Could you make XTend optional if it is required for only specific cases, for example? If not: Could I exclude XTend from delight-rhino-sandbox dependencies on my own or wouldn't it work anymore?

**Comment by mxro** [comment]
Thank you for raising the issue! Oh that is no good! Xtext dependencies were only used in a few places and I removed them in the commit above. Changes released in version `0.0.15` that should be available on Maven central soon.

Can you confirm the fix works for you? Thank you!

**Comment by gschnepp** [comment]
@mxro Looks good, thank you! Eliminating every incarnation of dependency hell is by definition a good job. 👍
