### ISSUE TITLE
license mismatch

### ISSUE THREAD

**Issue by bzaicsek-cxn** [javadelight/delight-rhino-sandbox#24]
Hi!

Your pom.xml contains GPL license, while your license TXT only mentions Apache and MIT. Could you clear this out?

**Comment by mxro** [comment]
Thank you for raising this issue. That one license was missed in the LICENSE.TXT - added it now, the project can be used under ANY of these licenses.

**Comment by bzaicsek-cxn** [comment]
Thank you! I was hoping for the complete removal, though... Could you add your last sentence to your LICENSE.TXT? I mean this:

> the project can be used under ANY of these licenses

Thank you in advance, and thank you for taking care of the issue in the first place!

**Comment by mxro** [comment]
@bzaicsek-cxn Done!

**Comment by bzaicsek-cxn** [comment]
thanks
