### ISSUE TITLE
Cast Object to String

### ISSUE THREAD

**Issue by pvinchon** [javadelight/delight-rhino-sandbox#7]
Hi,

Just started playing with your library, and I am wondering if there is a better way to cast the output from `.eval` to a `String`.

My current code is the follow:
```scala
import delight.rhinosandox.RhinoSandboxes
import org.mozilla.javascript.{Context => Rhino}

object Main extends App { 
    Rhino.enter
    try {
      val obj = RhinoSandboxes
        .create()
        .setInstructionLimit(1000)
        .setMaxDuration(1000)
        .eval("<cmd>", "['foo', 'bar']")

      Rhino.toString(obj)
    } finally {
      Rhino.exit
    }
}
```

Thanks for your help

**Comment by mxro** [comment]
Hi Philippe, thank you for your question.

.eval just returns whatever you would receive when using vanilla Rhino. So anything that works for Rhino, should work here as well.

One option might be if you already convert the result into a string in your JS code?

**Comment by pvinchon** [comment]
It is more on the Java/Scala side of things. Object, and asInstanceOf,
isn't really "safe" code.

I was unable to find anything in the javadoc, and was wondering if I missed
anything.

The code above works, but require Context to be entered, and exited. You
might of had something magic I could have used.

Anyways, great work on the lib, works wonders.

**Comment by mxro** [comment]
Thank you, glad that it is helpful!
